document.addEventListener(
  'DOMContentLoaded',
  function() {
    // click styling
    let buttonOne = d3.selectAll('#button-one')
    let buttonTwo = document.getElementById('button-two')
    let buttonThree = document.getElementById('button-three')
    let buttonFour = document.getElementById('button-four')
    let buttonFive = document.getElementById('button-five')
    let buttonSix = document.getElementById('button-six')
    let buttonSeven = document.getElementById('button-seven')
    let buttonEight = document.getElementById('button-eight')
    let buttonNine = document.getElementById('button-nine')
    buttonOne.classList.add('expand')
    buttonOne.addEventListener('click', () => {
      buttonOne.classList.add('expand')
      buttonTwo.classList.remove('expand')
      buttonThree.classList.remove('expand')
      buttonFour.classList.remove('expand')
      buttonFive.classList.remove('expand')
      buttonSix.classList.remove('expand')
      buttonSeven.classList.remove('expand')
      buttonEight.classList.remove('expand')
      buttonNine.classList.remove('expand')
    })

    buttonTwo.addEventListener('click', () => {
      buttonOne.classList.remove('expand')
      buttonTwo.classList.add('expand')
      buttonThree.classList.remove('expand')
      buttonFour.classList.remove('expand')
      buttonFive.classList.remove('expand')
      buttonSix.classList.remove('expand')
      buttonSeven.classList.remove('expand')
      buttonEight.classList.remove('expand')
      buttonNine.classList.remove('expand')
    })

    buttonThree.addEventListener('click', () => {
      buttonOne.classList.remove('expand')
      buttonTwo.classList.remove('expand')
      buttonThree.classList.add('expand')
      buttonFour.classList.remove('expand')
      buttonFive.classList.remove('expand')
      buttonSix.classList.remove('expand')
      buttonSeven.classList.remove('expand')
      buttonEight.classList.remove('expand')
      buttonNine.classList.remove('expand')
    })
    buttonFour.addEventListener('click', () => {
      buttonOne.classList.remove('expand')
      buttonTwo.classList.remove('expand')
      buttonThree.classList.remove('expand')
      buttonFour.classList.add('expand')
      buttonFive.classList.remove('expand')
      buttonSix.classList.remove('expand')
      buttonSeven.classList.remove('expand')
      buttonEight.classList.remove('expand')
      buttonNine.classList.remove('expand')
    })
    buttonFive.addEventListener('click', () => {
      buttonOne.classList.remove('expand')
      buttonTwo.classList.remove('expand')
      buttonThree.classList.remove('expand')
      buttonFour.classList.remove('expand')
      buttonFive.classList.add('expand')
      buttonSix.classList.remove('expand')
      buttonSeven.classList.remove('expand')
      buttonEight.classList.remove('expand')
      buttonNine.classList.remove('expand')
    })
    buttonSix.addEventListener('click', () => {
      buttonOne.classList.remove('expand')
      buttonTwo.classList.remove('expand')
      buttonThree.classList.remove('expand')
      buttonFour.classList.remove('expand')
      buttonFive.classList.remove('expand')
      buttonSix.classList.add('expand')
      buttonSeven.classList.remove('expand')
      buttonEight.classList.remove('expand')
      buttonNine.classList.remove('expand')
    })
    buttonSeven.addEventListener('click', () => {
      buttonOne.classList.remove('expand')
      buttonTwo.classList.remove('expand')
      buttonThree.classList.remove('expand')
      buttonFour.classList.remove('expand')
      buttonFive.classList.remove('expand')
      buttonSix.classList.remove('expand')
      buttonSeven.classList.add('expand')
      buttonEight.classList.remove('expand')
      buttonNine.classList.remove('expand')
    })
    buttonEight.addEventListener('click', () => {
      buttonOne.classList.remove('expand')
      buttonTwo.classList.remove('expand')
      buttonThree.classList.remove('expand')
      buttonFour.classList.remove('expand')
      buttonFive.classList.remove('expand')
      buttonSix.classList.remove('expand')
      buttonSeven.classList.remove('expand')
      buttonEight.classList.add('expand')
      buttonNine.classList.remove('expand')
    })
    buttonNine.addEventListener('click', () => {
      buttonOne.classList.remove('expand')
      buttonTwo.classList.remove('expand')
      buttonThree.classList.remove('expand')
      buttonFour.classList.remove('expand')
      buttonFive.classList.remove('expand')
      buttonSix.classList.remove('expand')
      buttonSeven.classList.remove('expand')
      buttonEight.classList.remove('expand')
      buttonNine.classList.add('expand')
    })
  },
  false
)
